Repository yeslee-v/42_minishell, pull requests merged in 2021-07, with the labels that each got.

#17 Jaekpark fix makefile
  Makefile
  srcs/main.c
  srcs/parse/lexer.c
  srcs/parse/parse.c
  srcs/parse/tokenizer.c
  srcs/utils/error.c
  srcs/utils/free.c
  srcs/utils/ft_utils.c
  srcs/utils/init.c
  srcs/utils/make_struct.c
Labels: enhancement

#18 [Fix] minishell.h
  includes/minishell.h
  srcs/builtin/blt_cd.c
  srcs/builtin/blt_echo.c
  srcs/builtin/blt_env.c
  srcs/builtin/blt_exit.c
  srcs/builtin/blt_export.c
  srcs/builtin/blt_pwd.c
  srcs/builtin/blt_unset.c
  srcs/builtin/init_blt.c
  srcs/pipe/pipe.c
  srcs/pipe/pipex.c
  srcs/pipe/redirect.c
  srcs/pipe/run.c
  srcs/pipe/set_cmd.c
Labels: enhancement

#20 Jaekpark refactor parising function
  Makefile
  includes/minishell.h
  libs/srcs/ft_strcmp.c
  srcs/main.c
  srcs/parse/lexer.c
  srcs/parse/parse.c
  srcs/parse/parser.c
  srcs/parse/tokenizer.c
  srcs/setup/set.c
  srcs/utils/error.c
  srcs/utils/free.c
  srcs/utils/ft_utils.c
  srcs/utils/init.c
  srcs/utils/make_struct.c
  srcs/utils/print.c
  tags
Labels: enhancement

#23 [fix] Makefile minishell.h main.c pipe_main.c set.c error.c free.c in…
  Makefile
  includes/minishell.h
  srcs/main.c
  srcs/pipe/pipe_main.c
  srcs/pipe/pipex.c
  srcs/setup/set.c
  srcs/utils/error.c
  srcs/utils/free.c
  srcs/utils/init.c
Labels: enhancement

#26 Jaekpark [Debug] lexer.c
  srcs/parse/lexer.c
Labels: bug, enhancement

#30 Yeslee [Update] blt_echo.c ver2
  srcs/builtin/blt_echo.c
Labels: bug, enhancement

#31 Yeslee [Update] blt_cd.c
  includes/minishell.h
  srcs/builtin/blt_cd.c
  srcs/builtin/init_blt.c
Labels: enhancement, help wanted, wontfix

#32 Yeslee [Fix] builtin functions
  Makefile
  includes/minishell.h
  srcs/builtin/blt_cd.c
  srcs/builtin/blt_echo.c
  srcs/builtin/blt_env.c
  srcs/builtin/blt_exit.c
  srcs/builtin/blt_export.c
  srcs/builtin/blt_pwd.c
  srcs/builtin/blt_unset.c
  srcs/builtin/init_blt.c
  srcs/builtin/print_env.c
  srcs/main.c
Labels: bug, enhancement

#35 Jaekpark [Fix] lexer.c tokenizer.c & [Add] fucntion for redir fd
  Makefile
  includes/minishell.h
  srcs/builtin/a.txt
  srcs/main.c
  srcs/parse/lexer.c
  srcs/parse/parser.c
  srcs/parse/tokenizer.c
  srcs/setup/set.c
  srcs/utils/a.txt
  srcs/utils/error.c
  srcs/utils/init.c
  srcs/utils/make_struct.c
  srcs/utils/print.c
  srcs/utils/utils.c
Labels: bug, enhancement

#37 Yeslee [Fix] builtin functions ver2
  includes/minishell.h
  srcs/builtin/blt_cd.c
  srcs/builtin/blt_export.c
  srcs/builtin/blt_pwd.c
  srcs/builtin/blt_unset.c
  srcs/builtin/init_blt.c
  srcs/builtin/print_env.c
  srcs/main.c
Labels: enhancement

#39 [Write] a function to delete ENV node & [Debug] segmentation fault
  includes/minishell.h
  srcs/main.c
  srcs/utils/utils.c
Labels: bug, enhancement

#40 Yeslee [Bug] segfault in blt_export.c
  Makefile
  includes/minishell.h
  srcs/builtin/blt_env.c
  srcs/builtin/blt_export.c
  srcs/builtin/blt_unset.c
  srcs/builtin/init_blt.c
  srcs/utils/utils.c
Labels: bug

#41 [Debug] Occurred segfaults when using export and unset command.
  srcs/builtin/blt_cd.c
  srcs/utils/utils.c
Labels: bug, enhancement

#42 Yeslee [Fix] relative path
  srcs/builtin/blt_cd.c
Labels: bug

#46 [Write] a function to get_pipe_count
  includes/minishell.h
  srcs/main.c
  srcs/utils/utils.c
Labels: enhancement

#47 Yeslee [Fix] heredoc and builtin functions
  Makefile
  includes/minishell.h
  srcs/builtin/a.txt
  srcs/builtin/blt_cd.c
  srcs/builtin/blt_echo.c
  srcs/builtin/blt_export.c
  srcs/builtin/blt_unset.c
  srcs/builtin/init_blt.c
  srcs/heredoc/hdoc_main.c
  srcs/heredoc/heredoc.c
  srcs/main.c
  srcs/pipe/multi_pipe.c
  srcs/pipe/pipe_main.c
  srcs/pipe/run.c
  srcs/pipe/set_cmd.c
  srcs/pipe/single_pipe.c
Labels: bug, help wanted, wontfix

#50 Jaekpark write function syntax error
  Makefile
  includes/minishell.h
  srcs/builtin/blt_echo.c
  srcs/heredoc/hdoc_main.c
  srcs/heredoc/heredoc.c
  srcs/main.c
  srcs/parse/lexer.c
  srcs/parse/parser.c
  srcs/parse/tokenizer.c
  srcs/setup/set.c
  srcs/utils/a.txt
  srcs/utils/free.c
  srcs/utils/init.c
  srcs/utils/make_struct.c
  srcs/utils/print.c
  srcs/utils/utils.c
Labels: enhancement

#51 Jaekpark [Fix] Norm v3
  Makefile
  includes/minishell.h
  includes/struct.h
  includes/variable.h
  srcs/ft_utils/ft_double_strjoin.c
  srcs/ft_utils/ft_is.c
  srcs/ft_utils/ft_strjoin_sp.c
  srcs/ft_utils/ft_strrdup.c
  srcs/heredoc/hdoc_main.c
  srcs/heredoc/heredoc.c
  srcs/main.c
  srcs/parse/analyze_syntax.c
  srcs/parse/analyze_token.c
  srcs/parse/lexer.c
  srcs/parse/parser.c
  srcs/parse/tokenizer.c
  srcs/parse/unclosed_pipe.c
  srcs/redirection/heredoc.c
  srcs/redirection/redirect.c
  srcs/setup/set.c
  srcs/signal/signal.c
  srcs/temp.c
  srcs/terminal/config.c
  srcs/terminal/cursor.c
  srcs/utils/delete_env.c
  srcs/utils/error.c
  srcs/utils/free.c
  srcs/utils/free_lst.c
  srcs/utils/free_struct.c
  srcs/utils/ft_utils.c
  srcs/utils/init.c
  srcs/utils/make_struct.c
  srcs/utils/print.c
  srcs/utils/print_error.c
  srcs/utils/print_utils.c
  srcs/utils/split_env.c
  srcs/utils/utils.c
Labels: enhancement

#52 Yeslee [Fix] pipe
  Makefile
  includes/minishell.h
  includes/struct.h
  srcs/builtin/blt_echo.c
  srcs/builtin/init_blt.c
  srcs/main.c
  srcs/pipe/init_pipe.c
  srcs/pipe/multi_pipe.c
  srcs/pipe/pipe_main.c
  srcs/pipe/run.c
  srcs/pipe/set_cmd.c
  srcs/pipe/single_pipe.c
Labels: bug, help wanted, wontfix

#53 Jaekpark [Write] a function for t_cmd
  .hdoc
  Makefile
  includes/minishell.h
  includes/struct.h
  includes/variable.h
  srcs/ft_utils/ft_strjoin_sp.c
  srcs/main.c
  srcs/parse/analyze_command.c
  srcs/parse/analyze_token.c
  srcs/parse/make_bin.c
  srcs/parse/parser.c
  srcs/parse/unclosed_pipe.c
  srcs/pipe/set_cmd.c
  srcs/redirection/heredoc.c
  srcs/redirection/redirect.c
  srcs/setup/set.c
  srcs/signal/signal.c
  srcs/terminal/cursor.c
  srcs/utils/free_struct.c
  srcs/utils/init.c
  srcs/utils/print_utils.c
Labels: enhancement

#54 Yeslee [Edit] execve
  Makefile
  includes/minishell.h
  includes/struct.h
  srcs/builtin/blt_cd.c
  srcs/builtin/blt_echo.c
  srcs/builtin/init_blt.c
  srcs/main.c
  srcs/pipe/init_pipe.c
  srcs/pipe/run.c
  srcs/pipe/set_cmd.c
  srcs/utils/blt_utils.c
Labels: bug, help wanted, wontfix

#55 yeslee [Fix] parameter in run_execve.c
  srcs/pipe/init_pipe.c
  srcs/pipe/run.c
Labels: help wanted

#56 Jaekpark [Fix] redirection & heredoc logic
  .hdoc
  .hdoc_0
  includes/minishell.h
  includes/struct.h
  includes/variable.h
  srcs/main.c
  srcs/parse/analyze_command.c
  srcs/parse/analyze_syntax.c
  srcs/parse/analyze_token.c
  srcs/parse/parser.c
  srcs/redirection/heredoc.c
  srcs/redirection/redirect.c
  srcs/signal/signal.c
  srcs/utils/error.c
  srcs/utils/free_lst.c
  srcs/utils/init.c
  srcs/utils/make_struct.c
  srcs/utils/print.c
  srcs/utils/print_utils.c
Labels: bug, enhancement

#59 Jaekpark [Fix] save exit_status when received signal and occurred redirection error
  .hdoc_0
  includes/struct.h
  includes/variable.h
  srcs/main.c
  srcs/parse/analyze_command.c
  srcs/redirection/redirect.c
  srcs/utils/print.c
  srcs/utils/print_utils.c
Labels: bug, enhancement

#60 Yeslee [Edit] run pipe
  .hdoc_0
  includes/minishell.h
  includes/struct.h
  srcs/builtin/init_blt.c
  srcs/main.c
  srcs/pipe/init_pipe.c
  srcs/pipe/multi_pipe.c
  srcs/pipe/pipe_main.c
  srcs/pipe/redirect.c
  srcs/pipe/run.c
  srcs/pipe/set_cmd.c
  srcs/pipe/single_pipe.c
  srcs/redirection/heredoc.c
Labels: wontfix

#61 Yeslee [Init] redirection
  Makefile
  includes/minishell.h
  srcs/builtin/init_blt.c
  srcs/pipe/init_pipe.c
  srcs/pipe/run.c
  srcs/redirection/run_redir.c
Labels: bug, question

#62 Jaekpark [Fix] add fd in t_cmd
  .hdoc_0
  includes/struct.h
  srcs/main.c
  srcs/parse/analyze_command.c
  srcs/utils/init.c
  srcs/utils/print.c
Labels: enhancement

#63 Jaekpark [debug] fix memory leaks
  srcs/main.c
  srcs/parse/make_bin.c
Labels: bug

#65 Jaepark [Write] a function for exit_status command and env auto convert
  includes/minishell.h
  srcs/builtin/blt_cd.c
  srcs/builtin/init_blt.c
  srcs/main.c
  srcs/parse/analyze_token.c
  srcs/parse/make_bin.c
  srcs/utils/error.c
  srcs/utils/print.c
Labels: bug, enhancement

#64 Yeslee [Add] exit_status in pipe, execve
  srcs/builtin/init_blt.c
  srcs/main.c
  srcs/pipe/init_pipe.c
  srcs/pipe/run.c
Labels: enhancement

#66 Yeslee [add] exit status in builtin
  Makefile
  includes/minishell.h
  includes/struct.h
  includes/variable.h
  srcs/builtin/blt_cd.c
  srcs/builtin/blt_env.c
  srcs/builtin/blt_export.c
  srcs/builtin/blt_pwd.c
  srcs/builtin/blt_unset.c
  srcs/builtin/init_blt.c
  srcs/main.c
  srcs/pipe/init_pipe.c
  srcs/pipe/run.c
  srcs/utils/print_error.c
Labels: duplicate

#67 Jaekpark [Fix] redirect , & handle quote syntax, ENVW
  Makefile
  includes/minishell.h
  includes/struct.h
  srcs/main.c
  srcs/parse/analyze_command.c
  srcs/parse/analyze_token.c
  srcs/parse/lexer.c
  srcs/parse/tokenizer.c
  srcs/redirection/redirect.c
  srcs/setup/set.c
  srcs/temp.c
  srcs/utils/make_struct.c
  srcs/utils/print.c
  srcs/utils/print_utils.c
Labels: bug, enhancement

#68 Yeslee [Edit] close in init_pipe.c
  Makefile
  srcs/builtin/blt_export.c
  srcs/builtin/init_blt.c
  srcs/main.c
  srcs/pipe/init_pipe.c
  srcs/redirection/run_redir.c
  srcs/utils/blt_utils.c
  srcs/utils/exit_status.c
Labels: bug, wontfix

#69 Jaekpark [Fix] env parse
  Makefile
  includes/minishell.h
  srcs/main.c
  srcs/parse/analyze_command.c
  srcs/parse/analyze_token.c
  srcs/parse/lexer.c
  srcs/parse/parser.c
  srcs/redirection/heredoc.c
  srcs/redirection/redirect.c
  srcs/utils/error.c
  srcs/utils/free_lst.c
  srcs/utils/free_struct.c
  srcs/utils/init.c
  srcs/utils/print.c
Labels: bug, enhancement

#70 Jaekpark [Fix] redirection & env parse
  srcs/parse/analyze_token.c
  srcs/redirection/redirect.c
Labels: bug, enhancement
