Repository yeslee-v/42_minishell, pull requests merged in 2021-08, with the labels that each got.

#71 Yeslee [Fix] redirection
  Makefile
  includes/minishell.h
  includes/variable.h
  srcs/builtin/blt_cd.c
  srcs/builtin/blt_env.c
  srcs/builtin/blt_exit.c
  srcs/builtin/blt_export.c
  srcs/builtin/blt_pwd.c
  srcs/builtin/blt_unset.c
  srcs/builtin/init_blt.c
  srcs/builtin/print_env.c
  srcs/main.c
  srcs/pipe/init_pipe.c
  srcs/pipe/run.c
  srcs/redirection/run_redir.c
  srcs/utils/blt_utils.c
Labels: bug

#72 Yeslee [error] redirection in 'cat > 1', 'cd >> 1'
  includes/minishell.h
  srcs/builtin/init_blt.c
  srcs/main.c
  srcs/pipe/init_pipe.c
  srcs/redirection/run_redir.c
Labels: bug

#73 Jaekpark [Write] a function handle signal in child process
  Makefile
  includes/minishell.h
  includes/struct.h
  libs/Makefile
  srcs/builtin/init_blt.c
  srcs/main.c
  srcs/parse/analyze_token.c
  srcs/pipe/init_pipe.c
  srcs/redirection/heredoc.c
  srcs/terminal/config.c
  srcs/terminal/cursor.c
  srcs/utils/free_lst.c
Labels: enhancement

#74 Yeslee [error] redir
  .gitignore
  Makefile
  includes/minishell.h
  includes/struct.h
  srcs/builtin/blt_cd.c
  srcs/builtin/init_blt.c
  srcs/main.c
  srcs/pipe/exec_pipe.c
  srcs/pipe/init_pipe.c
  srcs/redirection/run_redir.c
  srcs/utils/blt_utils.c
  srcs/utils/exit_status.c
Labels: enhancement

#77 Yeslee [Edit] Bugs
  includes/minishell.h
  includes/variable.h
  srcs/0_utils/error/exit_status.c
  srcs/3_execute/builtin/blt_echo.c
  srcs/3_execute/builtin/blt_export.c
  srcs/3_execute/builtin/blt_unset.c
  srcs/3_execute/builtin/init_blt.c
  srcs/main.c
Labels: enhancement

#78 Jaekpark [Fix] all error [Release Ver 1.0]
  Makefile
  includes/minishell.h
  includes/variable.h
  libs/includes/libft.h
  libs/srcs/ft_memccpy.c
  srcs/0_utils/error/error.c
  srcs/1_setup/setup.c
  srcs/1_setup/signal/exec_signal.c
  srcs/1_setup/signal/shell_signal.c
  srcs/3_execute/builtin/blt_cd.c
  srcs/3_execute/builtin/blt_exit.c
  srcs/3_execute/builtin/init_blt.c
  srcs/main.c
Labels: bug, enhancement

#80 Yeslee [error] redir
  srcs/0_utils/error/exit_status.c
  srcs/3_execute/builtin/blt_env.c
  srcs/3_execute/pipe/init_pipe.c
  srcs/utils/exit_status.c
Labels: enhancement

#82 Jaekpark [Write] a function for EOF
  Makefile
  includes/minishell.h
  includes/struct.h
  srcs/.temp.c
  srcs/1_setup/setup.c
  srcs/1_setup/signal/shell_signal.c
  srcs/1_setup/terminal/config.c
  srcs/1_setup/terminal/cursor.c
  srcs/2_parse/analyze_term_line.c
  srcs/2_parse/redirection/heredoc.c
  srcs/main.c
Labels: bug, enhancement

#83 Jaekpark [Fix] not_blt restore
  srcs/1_setup/signal/exec_signal.c
  srcs/3_execute/builtin/init_blt.c
Labels: bug
